#!/bin/bash

#
# Wrapper script to run cinder-manage to purge deleted records on active controller only
#
CINDER_PURGE_INFO="/var/run/cinder-purge.info"
CINDER_PURGE_CMD="/usr/bin/nice -n 2 /usr/bin/cinder-manage db purge 1 >>/dev/null 2>&1"

function is_active_pgserver()
{
    # Determine whether we're running on the same controller as the service.
    local service=postgres
    local enabledactive=$(/usr/bin/sm-query service $service| grep enabled-active)
    if [ "x$enabledactive" == "x" ]
    then
        # enabled-active not found for that service on this controller
        return 1
    else
        # enabled-active found for that resource
        return 0
    fi
}

if is_active_pgserver
then
    if [ ! -f ${CINDER_PURGE_INFO} ]
    then
        echo delay_count=0 > ${CINDER_PURGE_INFO}
    fi

    source ${CINDER_PURGE_INFO}
    sudo -u postgres psql -d sysinv -c "SELECT alarm_id, entity_instance_id from i_alarm;" | grep -P "^(?=.*100.101)(?=.*${HOSTNAME})" &>/dev/null
    if [ $? -eq 0 ]
    then
        source /etc/platform/platform.conf
        if [ "${system_type}" = "All-in-one" ]
        then
            source /etc/init.d/task_affinity_functions.sh
            idle_core=$(get_most_idle_core)
            if [ "$idle_core" -ne "0" ]
            then
                # Purge soft deleted records that are older than 1 day from cinder database.
                sh -c "exec taskset -c $idle_core ${CINDER_PURGE_CMD}"
                sed -i "/delay_count/s/=.*/=0/" ${CINDER_PURGE_INFO}
                exit 0
            fi
        fi

        if [ "$delay_count" -lt "3" ]
        then
            newval=$(($delay_count+1))
            sed -i "/delay_count/s/=.*/=$newval/" ${CINDER_PURGE_INFO}
            (sleep 3600; /usr/bin/cinder-purge-deleted-active) &
            exit 0
        fi
    fi

    # Purge soft deleted records that are older than 1 day from cinder database.
    eval ${CINDER_PURGE_CMD}
    sed -i "/delay_count/s/=.*/=0/" ${CINDER_PURGE_INFO}
fi

exit 0
