# List of packages to be included/installed in ISO
# If these have dependencies, they will be pulled in automatically
#

# ceph
ceph
ceph-common
ceph-fuse
ceph-radosgw
libcephfs1
python-cephfs
python-ceph-compat

# ceph-manager
ceph-manager

# openstack clients
python2-gnocchiclient
python2-ironicclient
python2-magnumclient
python2-muranoclient
python2-novaclient
python2-openstackclient

# openstack-ras
openstack-ras

# wrs-heat-templates
wrs-heat-templates

# python-django-horizon
python-django-horizon
openstack-dashboard

# stx-dashboard
starlingx-dashboard

# openstack-keystone
openstack-keystone

# distributedcloud
distributedcloud-dcmanager
distributedcloud-dcorch

# distributedcloud-client
distributedcloud-client-dcmanagerclient

# rabbitmq-server
rabbitmq-server
rabbitmq-server-config

# python-wsme
python2-wsme

# stx-ocf-scripts
stx-ocf-scripts

# openstack-barbican
openstack-barbican
openstack-barbican-api
openstack-barbican-common
openstack-barbican-keystone-listener
openstack-barbican-worker
puppet-barbican
python-barbican
python2-barbicanclient
python-ldap3
