#!/bin/bash

#
# Wrapper script to run nova-manage db purge_deleted_instances on active controller only
# also purges nova action events
#
NOVA_PURGE_INFO="/var/run/nova-purge.info"
NOVA_INSTANCE_PURGE_CMD="/usr/bin/nice -n 2 /usr/bin/nova-manage db purge_deleted_instances --older-than 1 >> /var/log/nova/nova-rowspurge.log 2>&1"
NOVA_EVENT_PURGE_CMD="/usr/bin/nice -n 2 /usr/bin/nova-manage db action_events_purge --keep-time-range 5  --max-events 1000 >> /var/log/nova/nova-rowspurge.log 2>&1"

function is_active_pgserver()
{
    # Determine whether we're running on the same controller as the service.
    local service=postgres
    local enabledactive=$(/usr/bin/sm-query service $service| grep enabled-active)
    if [ "x$enabledactive" == "x" ]
    then
        # enabled-active not found for that service on this controller
        return 1
    else
        # enabled-active found for that resource
        return 0
    fi
}

if is_active_pgserver
then
    if [ ! -f ${NOVA_PURGE_INFO} ]
    then
        echo delay_count=0 > ${NOVA_PURGE_INFO}
    fi

    source ${NOVA_PURGE_INFO}
    sudo -u postgres psql -d sysinv -c "SELECT alarm_id, entity_instance_id from i_alarm;" | grep -P "^(?=.*100.101)(?=.*${HOSTNAME})" &>/dev/null
    if [ $? -eq 0 ]
    then
        source /etc/platform/platform.conf
	if [ "${system_type}" = "All-in-one" ]
        then
            source /etc/init.d/task_affinity_functions.sh
            idle_core=$(get_most_idle_core)
            if [ "$idle_core" -ne "0" ]
            then
		# Purge soft deleted records that are older than 1 day and excess action events from nova database.
                sh -c "exec taskset -c $idle_core ${NOVA_INSTANCE_PURGE_CMD}"
		sh -c "exec taskset -c $idle_core ${NOVA_EVENT_PURGE_CMD}"
		sed -i "/delay_count/s/=.*/=0/" ${NOVA_PURGE_INFO}
                exit 0
            fi
        fi

        if [ "$delay_count" -lt "3" ]
        then
            newval=$(($delay_count+1))
            sed -i "/delay_count/s/=.*/=$newval/" ${NOVA_PURGE_INFO}
            (sleep 3600; /usr/bin/nova-purge-deleted-active) &
            exit 0
        fi
    fi

    # Purge soft deleted records that are older than 1 day and excess action events from nova database.
    eval ${NOVA_INSTANCE_PURGE_CMD}
    eval ${NOVA_EVENT_PURGE_CMD}
    sed -i "/delay_count/s/=.*/=0/" ${NOVA_PURGE_INFO}
fi

exit 0

